project:
  type: website
  output-dir: docs

website:
  title: "Betadiag"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts/Introduction/Introduction.qmd
        text: Introduction
      - href: posts/Installation/Installation.qmd
        text: Installation
      - href: posts/post-with-code/Example_code.qmd
        text: End-to-end demo

format:
  html:
    theme: cosmo
    css: styles.css

