project:
  type: website
  output-dir: docs

website:
  title: "Betadiag"
  navbar:
    logo: logo.png
    left:
      - href: index.qmd
        text: Home
      - href: subpages/Introduction.qmd
        text: Introduction
      - href: subpages/Installation.qmd
        text: Installation
      - href: subpages/Example_code.qmd
        text: End-to-end demo
        

format:
  html:
    theme: cosmo
    css: styles.css

