project:
  type: website
  output-dir: docs

website:
  title: "Betadiag"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: posts/Introduction/index.qmd
        text: Introduction
      - href: posts/post-with-code/index.qmd
        text: End-to-end demo

format:
  html:
    theme: cosmo
    css: styles.css

